/**
 * 
 * Copyright (c) 2014-2015, Openflexo
 * 
 * This file is part of Flexo-foundation, a component of the software infrastructure 
 * developed at Openflexo.
 * 
 * 
 * Openflexo is dual-licensed under the European Union Public License (EUPL, either 
 * version 1.1 of the License, or any later version ), which is available at 
 * https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 * and the GNU General Public License (GPL, either version 3 of the License, or any 
 * later version), which is available at http://www.gnu.org/licenses/gpl.html .
 * 
 * You can redistribute it and/or modify under the terms of either of these licenses
 * 
 * If you choose to redistribute it and/or modify under the terms of the GNU GPL, you
 * must include the following additional permission.
 *
 *          Additional permission under GNU GPL version 3 section 7
 *
 *          If you modify this Program, or any covered work, by linking or 
 *          combining it with software containing parts covered by the terms 
 *          of EPL 1.0, the licensors of this Program grant you additional permission
 *          to convey the resulting work. * 
 * 
 * This software is distributed in the hope that it will be useful, but WITHOUT ANY 
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 * PARTICULAR PURPOSE. 
 *
 * See http://www.openflexo.org/license.html for details.
 * 
 * 
 * Please contact Openflexo (openflexo-contacts@openflexo.org)
 * or visit www.openflexo.org if you need additional information.
 * 
 */

package org.openflexo.docgenerator.md;

import java.util.logging.Logger;

import org.openflexo.docgenerator.FetchRequestGenerator;
import org.openflexo.foundation.fml.editionaction.FetchRequest;
import org.openflexo.logging.FlexoLogger;
import org.openflexo.toolbox.StringUtils;

/**
 * Documentation generator for {@link FetchRequest}
 * 
 */
public class MDFetchRequestGenerator<FR extends FetchRequest<?, ?, ?>> extends FetchRequestGenerator<FR> {

	private static final Logger logger = FlexoLogger.getLogger(MDFetchRequestGenerator.class.getPackage().getName());

	public MDFetchRequestGenerator(Class<FR> objectClass, MDMasterGenerator<?> taDocGenerator) {
		super(objectClass, taDocGenerator);
	}

	@Override
	public MDMasterGenerator<?> getMasterGenerator() {
		return (MDMasterGenerator<?>) super.getMasterGenerator();
	}

	public String toMD(String text) {
		return getMasterGenerator().toMD(text);
	}

	@Override
	public String getTemplateName() {
		return "FetchRequest.md";
	}

	public String getSmallIconAsHTML() {
		return getMasterGenerator().getSmallIconAsHTML(getObjectClass());
	}

	public String getBigIconAsHTML() {
		return getMasterGenerator().getBigIconAsHTML(getObjectClass());
	}

	public String getLocalMDPath() {
		return getMasterGenerator().getLocalMDPath(getObjectClass());
	}

	public String getJavadocReference() {
		return getMasterGenerator().getJavadocReference(getObjectClass());
	}

	@Override
	public String generate() {

		StringBuffer sb = new StringBuffer();

		sb.append("# " + getFMLKeyword());
		sb.append(StringUtils.LINE_SEPARATOR);

		sb.append("[//]: # (Do not edit this file, which is automatically generated)" + StringUtils.LINE_SEPARATOR);
		sb.append(StringUtils.LINE_SEPARATOR);

		// sb.append("<h1><tt>" + getObjectClass().getSimpleName() + "</tt>" + getBigIconAsHTML() + "</h1>");

		// sb.append("<h1><tt>" + getObjectClass().getSimpleName() + "</tt>" + getBigIconAsHTML() + "</h1>");
		// sb.append(StringUtils.LINE_SEPARATOR);

		sb.append(getMasterGenerator().getBigIconAsHTML(getObjectClass()) + " " + getFMLDescription());
		sb.append(StringUtils.LINE_SEPARATOR);

		return render(sb);
	}

}
